server:
    port: 8080
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/event_mgmt_db
        username: springstudent
        password: springstudent
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MySQLDialect
        properties:
            hibernate:
                format_sql: true
            javax:
                persistence:
                    validation:
                        mode: none

        


    security:
        user:
            name: test
            password: test
logging:
    level:
        root: WARN
        com:
            baeldung: TRACE
